language: node_js
sudo: required
node_js:
- '4.1'
addons:
  ssh_known_hosts: stevenlyall.me
before_install:
- set -x
- openssl aes-256-cbc -K $encrypted_9a139472badc_key -iv $encrypted_9a139472badc_iv
  -in eval-n-deploy-key.enc -out eval-n-deploy-key -d
- rm eval-n-deploy-key.enc
- chmod 600 eval-n-deploy-key
- mv eval-n-deploy-key ~/.ssh/id_rsa
script:
- scripts/deploy.sh